import type { Metadata } from "next";
import "./globals.css";
import { righteous, googleSans } from "@/lib/fonts";
import Providers from "@/components/providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="fr"
            className={`${righteous.variable} ${googleSans.variable} h-full antialiased`}
            suppressHydrationWarning
        >
            <body className="min-h-full flex flex-col">
                 <Providers>{children}</Providers>
            </body>
        </html>
    );
}
